name: virpipe
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - pip
  - nextflow
  - biopython
  - r-base
  - r-argparser
  - r-rmarkdown
  - r-knitr 
  - r-dplyr
  - r-data.table
  - r-dt
  - r-ggplot2
  - r-kableextra